### ISSUE TITLE
L1C data download

### ISSUE THREAD

**Issue by rs9000** [ESA-PhiLab/PyRawS#22]
Hi,

I'm trying to download the L1C data associated with the RAW files to reconstruct the following folder structure:

./data/THRAWS/
raw: it will contain [decompressed raw](https://github.com/ESA-PhiLab/PyRawS#sentinel-2-raw-data).
l1c: it will contain [L1C](https://github.com/ESA-PhiLab/PyRawS#sentinel-2-l1c-data).

The file uploaded on Zenodo named L1C_files.json seems to contain a list of L0 files, such as: "S2A_OPER_MSI_L0__GR_VGS1_20210205T054020_S20210205T022636_D12_N02.09" etc..

How can I retrieve the names of associated L1C products in order to search and download them from Copernicus?

Thanks,
Rosario

**Comment by sirbastiano** [comment]
Hi,
Thanks for reaching out!

Sorry for the inconvenience, a wrong file was uploaded to Zenodo containing the list of RAW files. You can find the L1C files list here: https://github.com/ESA-PhiLab/PyRawS/blob/main/pyraws/database/L1C_files.json.

The L1C_files.json file will be modified soon on Zenodo platform!
