### ISSUE TITLE
THRAWS dataset setup

### ISSUE THREAD

**Issue by VarriAle17** [ESA-PhiLab/PyRawS#30]
In the README.md the info on how to configure THRAWS database is missing 
(e.g.: move the data downloaded from zenodo into the raw folder).
I found the useful info here instead:
https://ai4eo.esa.int/pyraws/notebooks/pyraws_Raw_API_demonstration.ipynb

**Comment by sirbastiano** [comment]
Dear @VarriAle17, we updated the readme. The configuration of pyraws can be found here: https://github.com/ESA-PhiLab/PyRawS/blob/main/quickstart/INSTALLATION.md

I am closing this issue. If you still encounter problems don't hesitate to reach out.
